# Generated by Django 5.1.4 on 2025-05-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
