# Generated by Django 5.1.4 on 2025-05-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_promo_active_product_promo_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge_color',
            field=models.CharField(blank=True, help_text="Tailwind class warna badge, misal: 'bg-primary/80', 'bg-secondary/80', 'bg-accent/80'", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_label',
            field=models.CharField(blank=True, help_text='Label badge produk, misal: New, Bestseller, Limited, Promo, dsb.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Stok produk yang tersedia'),
        ),
    ]
