# Generated by Django 5.1.4 on 2025-06-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_badge_color_alter_product_badge_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('minimalis', 'Minimalis'), ('glossy', 'Glossy'), ('cute', 'Cute'), ('glitter', 'Glitter')], max_length=20)),
            ],
        ),
    ]
