# Generated by Django 5.1.4 on 2025-06-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_paymentmethod_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(help_text='Durasi layanan (menit)'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_proof',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
    ]
