# Generated by Django 5.1.4 on 2025-06-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_booking_options_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Belum bayar'), ('waiting', 'Menunggu verifikasi'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='appointments.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(default='QRIS', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('service', 'date', 'time')},
        ),
    ]
